/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d0c5af',
        outline: '#99907c',
        'outline-variant': '#4d4635',
        primary: '#f2ca50',
        'on-primary': '#3c2f00',
        'primary-container': '#d4af37',
        secondary: '#ffb4a8',
        'secondary-container': '#920703',
        error: '#ffb4ab',
        background: '#131313',
        'obsidian-black': '#0A0A0A',
        'charcoal-haze': '#1A1A1A',
        'targaryen-crimson': '#B22222',
        'valyrian-steel': '#A8A8A8',
        'dragon-gold': '#FFD700',
      },
      fontFamily: {
        serif: ['"Source Serif 4"', 'Georgia', 'serif'],
        body: ['"Hanken Grotesk"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        gutter: '16px',
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
      },
      maxWidth: {
        story: '600px',
      },
    },
  },
  plugins: [],
};
